### ISSUE TITLE
flask_google_recaptcha module not work with new versions of Jinja2 (3.0.1+)

### ISSUE THREAD

**Issue by makhomed** [AndersonFirmino/flask-google-recaptcha#5]
fatal error:
```python
File "/home/www/example.com/app.py", line 18, in <module>
    from flask_google_recaptcha import GoogleReCaptcha
File "/usr/local/lib/python3.12/site-packages/flask_google_recaptcha/__init__.py", line 14, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.12/site-packages/jinja2/__init__.py)
```

detailed info of reason of bug: https://stackoverflow.com/a/71645733

Jinja2 changelog: https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-0-1

bugfix:
```diff
from flask import request
- from jinja2 import Markup
+ from markupsafe import Markup
from json import loads
```
